"""Add blockchain deployment fields to projects and payments

Revision ID: 62af17569fbd
Revises: 6ebaa392a429
Create Date: 2025-08-26 16:09:38.661846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62af17569fbd'
down_revision = '6ebaa392a429'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('blockchain_tx_hash', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('fundraising_goal', sa.Numeric(precision=15, scale=2), nullable=False))
    op.add_column('projects', sa.Column('token_deployment_tx', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('escrow_deployment_tx', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'escrow_deployment_tx')
    op.drop_column('projects', 'token_deployment_tx')
    op.drop_column('projects', 'fundraising_goal')
    op.drop_column('payments', 'blockchain_tx_hash')
    # ### end Alembic commands ### 