"""Remove fundraising_goal field from projects

Revision ID: 6464672634e7
Revises: 62af17569fbd
Create Date: 2025-08-26 16:18:04.266039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6464672634e7'
down_revision = '62af17569fbd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'fundraising_goal')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('fundraising_goal', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False))
    # ### end Alembic commands ### 